taxi/urls.py
from django.urls import path, include
from rest_framework import routers


from .views import (
    index,
    CarListView,
    CarDetailView,
    DriverListView,
    DriverDetailView,
    ManufacturerListView,
    car_create_view,
    ManufacturerDetailView,
    ManufacturerCreateView,
    CarUpdateView, ManufacturerUpdateView,
    CarDeleteView,
    ManufacturerDeleteView,
    DriverCreateView,
    DriverUpdateView,
    DriverDeleteView,

    DriverViewSet,
)
router = routers.DefaultRouter()

router.register('driver', DriverViewSet)

urlpatterns = [
    path("api/", include(router.urls)),
    path("", index, name="index"),

    path("manufacturers/", ManufacturerListView.as_view(), name="manufacturer-list"),
    path("manufacturers/<int:pk>", ManufacturerDetailView.as_view(), name="manufacturer-detail"),
    path("manufacturers/create/", ManufacturerCreateView.as_view(), name="manufacturer-create"),
    path("manufacturers/update/<int:pk>", ManufacturerUpdateView.as_view(), name="manufacturer-update"),
    path("manufacturers/delete/<int:pk>", ManufacturerDeleteView.as_view(), name="manufacturer-delete"),

    path("cars/", CarListView.as_view(), name="car-list"),
    path("cars/<int:pk>/", CarDetailView.as_view(), name="car-detail"),
    path("cars/create/", car_create_view, name="car-create"),
    path("cars/update/<int:pk>", CarUpdateView.as_view(), name="car-update"),
    path("cars/delete/<int:pk>", CarDeleteView.as_view(), name="car-delete"),

    path("drivers/", DriverListView.as_view(), name="driver-list"),
    path("drivers/<int:pk>/", DriverDetailView.as_view(), name="driver-detail"),
    path("drivers/create/", DriverCreateView.as_view(), name="driver-create"),
    path("drivers/update/<int:pk>", DriverUpdateView.as_view(), name="driver-update"),
    path("drivers/delete/<int:pk>", DriverDeleteView.as_view(), name="driver-delete"),

]

app_name = "taxi"

taxi_service/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django_registration.backends.one_step.views import RegistrationView

from taxi.forms import DriverForm

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("taxi.urls", namespace="taxi")),
    path('__debug__/', include('debug_toolbar.urls')),
    path('accounts/', include("django_registration.backends.one_step.urls")),
    path("accounts/", include("django.contrib.auth.urls")),
    path('accounts/register', RegistrationView.as_view(
        form_class=DriverForm,
    ), name='django_registration_register')
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

taxi/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.urls import reverse


class Manufacturer(models.Model):
    name = models.CharField(max_length=255)
    country = models.CharField(max_length=255)

    class Meta:
        ordering = ["name"]

    def __str__(self):
        return f"{self.name} {self.country}"


class Driver(AbstractUser):
    license_number = models.CharField(max_length=255, unique=True)

    class Meta:
        verbose_name = "driver"
        verbose_name_plural = "drivers"
        ordering = ['date_joined']

    def __str__(self):
        return f"{self.username} ({self.first_name} {self.last_name})"

    def get_absolute_url(self):
        return reverse("taxi:driver-detail", kwargs={'pk': self.pk})


class Car(models.Model):
    model = models.CharField(max_length=255)
    manufacturer = models.ForeignKey(Manufacturer, on_delete=models.CASCADE)
    drivers = models.ManyToManyField(Driver, related_name="cars")

    class Meta:
        ordering = ['model']

    def __str__(self):
        return self.model

taxi/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm

from .models import Driver, Car



class DriverForm(UserCreationForm):
    class Meta:
        model = Driver
        fields = ["username", "password1", "password2", "email", "license_number"]
        widgets = {
            'password':  forms.PasswordInput(),
        }


class CarForm(forms.ModelForm):
    class Meta:
        model = Car
        fields = ["manufacturer", "model"]


class CarSearchForm(forms.Form):
    name = forms.CharField(
        max_length=255,
        required=False,
    )

taxi/views.py
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views import generic
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from rest_framework import viewsets

from .forms import CarForm, CarSearchForm
from .models import Driver, Car, Manufacturer
from .serializers import DriverSerializer

DENIED_PERMISSION_MESSAGE = "You need to have admin status to view this page"


def index(request):
    """View function for the home page of the site."""

    num_drivers = Driver.objects.count()
    num_cars = Car.objects.count()
    num_manufacturers = Manufacturer.objects.count()

    num_visits = request.session.get("num_visits", 0)
    request.session["num_visits"] = num_visits + 1

    context = {
        "num_drivers": num_drivers,
        "num_cars": num_cars,
        "num_manufacturers": num_manufacturers,
        "num_visits": num_visits,
    }

    return render(request, "taxi/index.html", context=context)


class ManufacturerListView(generic.ListView):
    model = Manufacturer
    context_object_name = "manufacturer_list"
    template_name = "taxi/manufacturer_list.html"
    paginate_by = 2


class ManufacturerCreateView(generic.CreateView):
    model = Manufacturer
    context_object_name = "form"
    fields = ["name", "country"]
    template_name = "taxi/manufacturer_form.html"

    def get_success_url(self):
        return reverse_lazy("taxi:manufacturer-detail", kwargs={"pk":self.object.id})


class ManufacturerDetailView(generic.DetailView):
    model = Manufacturer
    template_name = "taxi/manufacturer_detail.html"


class ManufacturerUpdateView(generic.UpdateView):
    model = Manufacturer
    fields = "__all__"
    template_name = "taxi/manufacturer_form.html"

    def get_success_url(self):
        return reverse_lazy("taxi:manufacturer-detail", kwargs={"pk": self.object.id})


class ManufacturerDeleteView(generic.DetailView):
    model = Manufacturer


class CarListView(generic.ListView):
    model = Car
    paginate_by = 2
    queryset = Car.objects.all().select_related("manufacturer")

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)

        context["search_form"] = CarSearchForm()

        return context

    def get_queryset(self):
        name = self.request.GET.get('name')

        if name:
            return self.queryset.filter(model__icontains=name)

        return self.queryset


class CarDetailView(generic.DetailView):
    model = Car


def car_create_view(request):
    if request.method == "POST":
        car_form = CarForm(request.POST)

        car = None
        if car_form.is_valid():
            car = Car.objects.create(**car_form.cleaned_data)
            car.drivers.add(request.user)
        else:
            return render(
                request=request,
                template_name="taxi/car_form.html",
                context={"error": True, "form": car_form},
            )
        if car:
            return redirect(reverse_lazy("taxi:car-detail", kwargs={"pk":car.id}))
        else:
            return HttpResponse(status=501)

    elif request.method == "GET":
        return render(
            request=request,
            template_name="taxi/car_form.html",
            context={"form": CarForm()},
        )


class CarUpdateView(generic.UpdateView):
    model = Car
    template_name = "taxi/car_form.html"
    fields = "__all__"

    def get_success_url(self):
        return reverse_lazy("taxi:car-detail", kwargs={"pk": self.object.id})


class CarDeleteView(generic.DeleteView):
    model = Car
    success_url = reverse_lazy("taxi:car-list")


class DriverListView(generic.ListView):
    model = Driver
    paginate_by = 2
    queryset = Driver.objects.filter(is_staff=False)


class DriverDetailView(generic.DetailView):
    model = Driver
    queryset = Driver.objects.all().prefetch_related("cars__manufacturer")


class DriverCreateView(PermissionRequiredMixin, generic.CreateView):
    permission_required = 'taxi.admin'
    permission_denied_message = DENIED_PERMISSION_MESSAGE

    model = Driver
    fields = "__all__"
    template_name = "taxi/manufacturer_form.html"

    def get_success_url(self):
        return reverse_lazy("taxi:car-detail", kwargs={"pk": self.object.id})


class DriverUpdateView(PermissionRequiredMixin, generic.CreateView):
    permission_required = 'taxi.change_driver'
    permission_denied_message = DENIED_PERMISSION_MESSAGE

    model = Driver
    fields = "__all__"
    template_name = "taxi/manufacturer_form.html"

    def get_success_url(self):
        return reverse_lazy("taxi:car-detail", kwargs={"pk": self.object.id})


class DriverDeleteView(PermissionRequiredMixin, generic.DeleteView):
    permission_required = 'taxi.delete_driver'
    permission_denied_message = DENIED_PERMISSION_MESSAGE

    model = Driver
    success_url = reverse_lazy("taxi:driver-list")


# API Views

class DriverViewSet(viewsets.ModelViewSet):
    queryset = Driver.objects.all()
    serializer_class = DriverSerializer

templates/taxi/car_confirm_delete.html
{% extends 'base.html' %}


{% block content %}
    {% include "includes/default_delete.html" %}
{% endblock %}

templates/taxi/car_detail.html
{% extends "base.html" %}

{% block content %}
  <p><a href="{% url 'taxi:manufacturer-detail' pk=car.manufacturer.id%}">Manufacturer</a>:
      ({{ car.manufacturer.name }}, {{ car.manufacturer.country }})</p>
  <p>Model: {{ car.model }}</p>
    <p><a href="{% url 'taxi:car-update' pk=car.id%}">Update</a></p>
    <p><a href="{% url 'taxi:car-delete' pk=car.id%}">Delete</a></p>
  <h1>Drivers</h1>
  <hr>
  <ul>
  {% for driver in car.drivers.all %}
    <li>{{ driver.username }} ({{ driver.first_name }} {{ driver.last_name }})</li>
  {% endfor %}
  </ul>
{% endblock %}

templates/taxi/car_form.html
{% extends "base.html" %}

{% block content %}
    {% include "includes/default_post_form.html" %}
{% endblock %}

templates/taxi/car_list.html
{% extends "base.html" %}

{% block content %}
  <h1>Car list</h1>
    <a href="{% url 'taxi:car-create' %}" class="button">New car</a>
  {% if car_list %}
      <form action="" method="get">
      {% csrf_token %}
      {{ search_form.as_p }}
          <input type="submit" value="Search" class="btn">
      </form>
    <ul>
      {% for car in car_list %}
        <li>
          <a href="{% url "taxi:car-detail" pk=car.id %} ">{{ car.id }}</a>
          {{ car.model }} ({{ car.manufacturer.name }})
            <a href="{% url 'taxi:car-update' pk=car.id%}">Update</a>
            <a href="{% url 'taxi:car-delete' pk=car.id%}">Delete</a>
        </li>

      {% endfor %}
    </ul>
  {% else %}
    <p>There are no cars in taxi</p>
  {% endif %}
{% endblock %}

templates/taxi/driver_detail.html
{% extends "base.html" %}

{% block content %}
  <h1>
    Username: {{ driver.username }}
  </h1>

  <p><strong>First name:</strong> {{ driver.first_name }}</p>
  <p><strong>Last name:</strong> {{ driver.last_name }}</p>
  <p><strong>License number:</strong> {{ driver.license_number }}</p>
  <p><strong>Is staff:</strong> {{ driver.is_staff }}</p>

  <div class="ml-3">
    <h4>Cars</h4>

    {% for car in driver.cars.all %}
        <hr>
        <p><strong>Model:</strong> {{ car.model }}</p>
        <p><strong>Manufacturer:</strong> {{ car.manufacturer.name }}</p>
        <p class="text-muted"><strong>Id:</strong> {{car.id}}</p>

    {% empty %}
      <p>No cars!</p>
    {% endfor %}
  </div>
{% endblock %}

templates/taxi/driver_form.html
{% extends "base.html" %}


{% block content %}
    {% include "includes/default_post_form.html" %}
{% endblock %}

templates/taxi/driver_list.html
{% extends "base.html" %}

{% block content %}
    <h1>Driver List
    </h1>
    {% if perms.taxi.create_driver %}
        <a href="{% url 'taxi:driver-create' %}">Create New Driver</a>
    {% endif %}
    {% if driver_list %}
    <table class="table">
      <tr>
        <th>ID</th>
        <th>Username</th>
        <th>First name</th>
        <th>Last name</th>
        <th>License number</th>
      {% if perms.taxi.change_driver %}
        <th>Update</th>
      {% endif %}
      {% if perms.taxi.delete_driver %}
        <th>Delete</th>
      {% endif %}
      </tr>
    {% for driver in driver_list %}
      <tr>
        <td>{{ driver.id }}</td>
        <td><a href="{{ driver.get_absolute_url }}">{{ driver.username }} {% if user == driver %} (Me){% endif %}</a></td>
        <td>{{ driver.first_name }}</td>
        <td>{{ driver.last_name }}</td>
        <td>{{ driver.license_number }}</td>
          {% if perms.taxi.change_driver %}
            <td><a href="{% url 'taxi:driver-update' pk=driver.id%}">Update</a></td>
          {% endif %}
        {% if perms.taxi.create_driver %}
            <td><a href="{% url 'taxi:driver-delete' pk=driver.id%}">Delete</a></td>
        {% endif %}
      </tr>
    {% endfor %}

    </table>
    {% else %}
      <p>There are no drivers in the service.</p>
    {% endif %}
{% endblock %}

templates/taxi/index.html
{% extends "base.html" %}

{% block content %}
    <h1>Taxi Service Home</h1>
    <p>Welcome to Best Taxi Ever!</p>
    <h2>Dynamic content</h2>
    <p>The Taxi service has the following record counts:</p>
    <ul>
        <li><strong>Cars:</strong> {{ num_cars }}</li>
        <li><strong>Drivers:</strong> {{ num_drivers }}</li>
        <li><strong>Manufacturers:</strong> {{ num_manufacturers }}</li>
    </ul>

    <p>You have visited this page
        {{ num_visits }} time{{ num_visits|pluralize }}.
    </p>

{% endblock %}

templates/taxi/manufacturer_confirm_delete.html
{% extends "base.html" %}


{% block content %}
    {% include "includes/default_delete.html" %}
{% endblock %}

templates/taxi/manufacturer_detail.html
{% extends "base.html" %}

{% block title %}
    <title>
        Manufacturer:{{ manufacturer.id }}
    </title>
{% endblock %}

{% block content %}
    <ul class="list-group">
        <li>Name: {{ manufacturer.name }}</li>
        <li>Country: {{ manufacturer.country }}</li>
    </ul>
    Back to all manufacturers <a href="{% url 'taxi:manufacturer-list' %}">list</a>
{% endblock %}

templates/taxi/manufacturer_form.html
{% extends 'base.html' %}


{% block content %}
    {% include "includes/default_post_form.html" %}
{% endblock %}

templates/taxi/manufacturer_list.html
{% extends "base.html" %}

{% block content %}
    <h1>Manufacturer List
    </h1>
    <a href="{% url 'taxi:manufacturer-create' %}" class="button">New Manufacturer</a>

    {% if manufacturer_list %}
      <table class="table">
        <tr>
          <th>ID</th>
          <th>Name</th>
          <th>Country</th>
          <th>Update</th>
          <th>Delete</th>
        </tr>

        {% for manufacturer in manufacturer_list %}
            <tr>
              <td>
                  <a href="{% url 'taxi:manufacturer-detail' pk=manufacturer.id%}">{{ manufacturer.id }}</a>
              </td>
              <td>
                  {{ manufacturer.name }}
              </td>
              <td>
                  {{ manufacturer.country }}
              </td>
                <td>
                    <a href="{% url 'taxi:manufacturer-update' pk=manufacturer.id%}">Update</a>
                </td>
                <td>
                    <a href="{% url 'taxi:manufacturer-delete' pk=manufacturer.id%}">Delete</a>
                </td>
          </tr>
        {% endfor %}
      </table>

    {% else %}
        <p>There are no manufacturers in the service.</p>
    {% endif %}
{% endblock %}