taxi/urls.py
from django.urls import path, include
from rest_framework import routers


from .views import (
    index,
    CarListView,
    CarDetailView,
    DriverListView,
    DriverDetailView,
    ManufacturerListView,
    car_create_view,
    ManufacturerDetailView,
    ManufacturerCreateView,
    CarUpdateView, ManufacturerUpdateView,
    CarDeleteView,
    ManufacturerDeleteView,
    DriverCreateView,
    DriverUpdateView,
    DriverDeleteView,

    DriverViewSet,
)
router = routers.DefaultRouter()

router.register('driver', DriverViewSet)

urlpatterns = [
    path("api/", include(router.urls)),
    path("", index, name="index"),

    path("manufacturers/", ManufacturerListView.as_view(), name="manufacturer-list"),
    path("manufacturers/<int:pk>", ManufacturerDetailView.as_view(), name="manufacturer-detail"),
    path("manufacturers/create/", ManufacturerCreateView.as_view(), name="manufacturer-create"),
    path("manufacturers/update/<int:pk>", ManufacturerUpdateView.as_view(), name="manufacturer-update"),
    path("manufacturers/delete/<int:pk>", ManufacturerDeleteView.as_view(), name="manufacturer-delete"),

    path("cars/", CarListView.as_view(), name="car-list"),
    path("cars/<int:pk>/", CarDetailView.as_view(), name="car-detail"),
    path("cars/create/", car_create_view, name="car-create"),
    path("cars/update/<int:pk>", CarUpdateView.as_view(), name="car-update"),
    path("cars/delete/<int:pk>", CarDeleteView.as_view(), name="car-delete"),

    path("drivers/", DriverListView.as_view(), name="driver-list"),
    path("drivers/<int:pk>/", DriverDetailView.as_view(), name="driver-detail"),
    path("drivers/create/", DriverCreateView.as_view(), name="driver-create"),
    path("drivers/update/<int:pk>", DriverUpdateView.as_view(), name="driver-update"),
    path("drivers/delete/<int:pk>", DriverDeleteView.as_view(), name="driver-delete"),

]

app_name = "taxi"

taxi_service/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django_registration.backends.one_step.views import RegistrationView

from taxi.forms import DriverForm

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("taxi.urls", namespace="taxi")),
    path('__debug__/', include('debug_toolbar.urls')),
    path('accounts/', include("django_registration.backends.one_step.urls")),
    path("accounts/", include("django.contrib.auth.urls")),
    path('accounts/register', RegistrationView.as_view(
        form_class=DriverForm,
    ), name='django_registration_register')
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

templates/includes/default_delete.html
<form action="" method="post">
    {% csrf_token %}
    Do you want to delete {{ object }}?
    <input type="submit" value="Delete">
</form>

templates/includes/default_post_form.html
<form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    {% if object %}
        <input type="submit" value="Update" class="button">
    {% else %}
        <input type="submit" value="Create" class="button">
    {% endif %}
</form>

templates/includes/pagination.html
{% load url_patcher %}
{% if is_paginated %}
  <ul class="pagination">
    {% if page_obj.has_previous %}
      <li class="page-item">
        <a href="{% append_get_url request page=page_obj.previous_page_number %}" class="page-link">prev</a>
      </li>
    {% endif %}
    <li class="page-item active">
      <span class="page-link">{{ page_obj.number }} of {{ paginator.num_pages }}</span>
    </li>
    {% if page_obj.has_next %}
      <li class="page-item">
        <a href="{% append_get_url request page=page_obj.next_page_number %}" class="page-link">next</a>
      </li>
    {% endif %}
  </ul>
{% endif %}

templates/includes/sidebar.html
<ul class="sidebar-nav list-group">
  {% if user.is_authenticated %}
    <li class="list-group-item">User: <a href="{{ user.get_absolute_url }}">{{ user.get_username }}</a></li>
    <li class="list-group-item"><a href="{% url 'logout'%}?next={{request.path}}">Logout</a></li>
  {% else %}
    <li class="list-group-item"><a href="{% url 'login'%}?next={{request.path}}">Login</a></li>
    <li class="list-group-item"><a href="{% url 'django_registration_register'%}?next={{request.path}}">Register</a></li>
  {% endif %}

  <br>

  <li class="list-group-item"><a href="{% url 'taxi:index' %}">Home</a></li>
  <li class="list-group-item"><a href="{% url 'taxi:driver-list' %}">All drivers</a></li>
  <li class="list-group-item"><a href="{% url 'taxi:car-list' %}">All cars</a></li>
  <li class="list-group-item"><a href="{% url 'taxi:manufacturer-list' %}">All manufacturers</a></li>
  <li class="list-group-item mt-auto"><a href="{% url 'taxi:api-root' %}">API</a></li>

</ul>